### PR TITLE
Fixed limit input

### PR DESCRIPTION
**Pull request by dylanrainwater**
Limit inputs will now no longer accept invalid options and FR questions will now automatically detect if the answer was correct or not instead of asking the user.

### CODE REVIEW

**Comment by wlifferth** [comment]
Looking good! Only one snag for me: for FR questions asking the user if it was correct was useful because it allowed flexibility (if I got the gist of a definition correct, I can still give myself the point). That case isn't readily apparent in the quiz generated by example.md, but it's common in notes with longer values.

**Comment by wlifferth** [comment]
Fixing bad input for limit is golden though.

**Comment by dylanrainwater** [comment]
Ah okay! Sorry about that. I un-smartified the FR questions, didn't realize that was a wanted feature my bad.

**Comment by dylanrainwater** [comment]
Sorry for all of the commits. I made a few mistakes..

**Comment by wlifferth** [comment]
You're totally fine--that's really mostly based on my use cases. Can you squash all the commits into one with git rebase? Other than that lgtm.

**Pull request closed without merging**
